openapi: 3.1.0
info:
  version: 1.0.0
  title: E-Pharmacy app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is the documentation of E-Pharmacy - a web platform for online pharmacies.
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url:
  - url: http://localhost:4000/api
paths:
  # ендпоінти авторизації
  /api/user/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /api/user/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /api/user/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /api/user/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  # ендпоінти по роботі з користувачами
  /api/user/user-info:
    get:
      $ref: ../swagger/paths/auth/getUserInfo.yaml

  # ендпоінти, що повертає відгуки користувачів
  /api/customer-reviews:
    get:
      $ref: ../swagger/paths/reviews/getAllReviews.yaml

  # ендпоінти по роботі з аптеками
  /api/stores:
    get:
      $ref: ../swagger/paths/pharmacies/getAllPharmacies.yaml
  /api/stores/nearest:
    get:
      $ref: ../swagger/paths/pharmacies/getPharmaciesNearest.yaml

    # ендпоінти по роботі з ліками
  /api/products:
    get:
      $ref: ../swagger/paths/products/getAllProducts.yaml
  /api/products/{productId}:
    get:
      $ref: ../swagger/paths/products/getOneProductId.yaml

    # ендпоінти по роботі з товарами у кошику
  /api/cart:
    get:
      $ref: ../swagger/paths/carts/getCartItems.yaml
  /api/cart/update:
    put:
      $ref: ../swagger/paths/carts/updateCart.yaml
  /api/cart/checkout:
    post:
      $ref: ../swagger/paths/carts/checkoutCart.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
